version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
      - "8001:81"
      - "8002:82"
      - "8003:83"
      - "8004:84"
      - "8005:85"
    depends_on:
      - php71
      - php72
      - php73
      - php74
    volumes:
      - "$PWD/lnmp/nginx/conf.d:/etc/nginx/conf.d"
      - "$PWD/lnmp/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/wwwroot:/usr/share/nginx/html"
      - "$PWD/lnmp/logs/nginx:/var/log/nginx"
    networks:
      - app_net
    container_name: "lnmp-nginx"
  php71:
    build: ./php/php71
    ports: ["9001"]
    links:
      - mysql
    volumes:
      - "$PWD/wwwroot:/var/www/html"
      - "$PWD/lnmp/php71/php.ini:/usr/local/etc/php/php.ini"
      - "$PWD/lnmp/php71/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "$PWD/lnmp/php71/logs/php-fpm/:/var/log/php-fpm/"
    networks:
      - app_net
    container_name: "lnmp-php7.1"
  php72:
    build: ./php/php72
    ports: [ "9002" ]
    links:
      - mysql
    volumes:
      - "$PWD/wwwroot:/var/www/html"
      - "$PWD/lnmp/php72/php.ini:/usr/local/etc/php/php.ini"
      - "$PWD/lnmp/php72/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "$PWD/lnmp/php72/log/:/var/log/php-fpm/"
    networks:
      - app_net
    container_name: "lnmp-php7.2"
  php73:
    build: ./php/php73
    ports: [ "9003" ]
    links:
      - mysql
    volumes:
      - "$PWD/wwwroot:/var/www/html"
      - "$PWD/lnmp/php73/php.ini:/usr/local/etc/php/php.ini"
      - "$PWD/lnmp/php73/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "$PWD/lnmp/php73/log/:/var/log/php-fpm/"
    networks:
      - app_net
    container_name: "lnmp-php7.3"
  php74:
      build: ./php/php74
      ports: [ "9004" ]
      links:
        - mysql
      volumes:
        - "$PWD/wwwroot:/var/www/html"
        - "$PWD/lnmp/php74/php.ini:/usr/local/etc/php/php.ini"
        - "$PWD/lnmp/php74/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
        - "$PWD/lnmp/php74/log/:/var/log/php-fpm/"
      networks:
        - app_net
      container_name: "lnmp-php7.4"
  mysql:
    image: mysql:5.7

    ports:
        - ${MYSQL_HOST_PORT}:3306
    volumes:
        - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - app_net
    container_name: "lnmp-mysql5.7"
networks:
  app_net: